--[[TEACH IT EASY, an educational games platform
    Copyright (C) 2015  Linköping University

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.


    MIT LICENSE:
    Copyright (c) 2015 Zenterio AB

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:



    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.


    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    THE SOFTWARE.


    ]]
--
-- Created by IntelliJ IDEA.
-- User: jonathan
-- Date: 2015-11-26
-- Time: 10:55
-- To change this template use File | Settings | File Templates.
--

lunit = require "lunit"
module( "Main_test", package.seeall, lunit.testcase )

function setup()
    clear_mock()
    main = require ("main") -- import the main file
end

-------------------------------------
-- System test 1
-- Run the first level
-- @system_under_test: main.lua
-- @author name: Andreas Mansson & Jonathan Anderson
-------------------------------------
function test_file()

    onStart()
--    onKey("ok","down")
--    onKey("ok","down")
--    onKey("ok","down")
--    -- for key,value in pairs(platformContext.game.bottomMenu.character) do print(key,value) end
--
--    onKey("1","down")
--    onKey("1","down")
--    onKey("1","down")
--    onKey("1","down")
--    onKey("3","down")
--    onKey("1","down")
--    onKey("1","down")
--    onKey("3","down")
--    onKey("1","down")
--    onKey("2","down")
--    onKey("1","down")
--    onKey("3","down")
--    onKey("1","down")
--    onKey("0","down")

    local cnt = 236
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',1/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',2/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',3/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',4/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',5/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',6/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',7/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',8/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',9/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',10/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',11/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',12/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',13/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',14/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',15/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',16/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',17/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',18/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',19/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',20/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',21/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',22/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',23/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',24/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',25/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',26/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',27/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',28/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',29/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',30/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',31/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',32/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',33/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',34/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',35/cnt*100)) .. '%' .. ' )'))
    onKey('up','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',36/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',37/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',38/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',39/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',40/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',41/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',42/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',43/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',44/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',45/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',46/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',47/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',48/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',49/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',50/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',51/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',52/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',53/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',54/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',55/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',56/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',57/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',58/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',59/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',60/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',61/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',62/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',63/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',64/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',65/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',66/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',67/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',68/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',69/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',70/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',71/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',72/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',73/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',74/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',75/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',76/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',77/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',78/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',79/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',80/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',81/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',82/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',83/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',84/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',85/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',86/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',87/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',88/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',89/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',90/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',91/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',92/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',93/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',94/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',95/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',96/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',97/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',98/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',99/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',100/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',101/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',102/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',103/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',104/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',105/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',106/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',107/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',108/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',109/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',110/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',111/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',112/cnt*100)) .. '%' .. ' )'))
    onKey('back','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',113/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',114/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',115/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',116/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',117/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',118/cnt*100)) .. '%' .. ' )'))
    onKey('up','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',119/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',120/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',121/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',122/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',123/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',124/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',125/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',126/cnt*100)) .. '%' .. ' )'))
    onKey('back','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',127/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',128/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',129/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',130/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',131/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',132/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',133/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',134/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',135/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',136/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',137/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',138/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',139/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',140/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',141/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',142/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',143/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',144/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',145/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',146/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',147/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',148/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',149/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',150/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',151/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',152/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',153/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',154/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',155/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',156/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',157/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',158/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',159/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',160/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',161/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',162/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',163/cnt*100)) .. '%' .. ' )'))
    onKey('down','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',164/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',165/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',166/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',167/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',168/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',169/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',170/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',171/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',172/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',173/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',174/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',175/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',176/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',177/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',178/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',179/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',180/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',181/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',182/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',183/cnt*100)) .. '%' .. ' )'))
    onKey('7','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',184/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',185/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',186/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',187/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',188/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',189/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',190/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',191/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',192/cnt*100)) .. '%' .. ' )'))
    onKey('8','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',193/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',194/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',195/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',196/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',197/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',198/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',199/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',200/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',201/cnt*100)) .. '%' .. ' )'))
    onKey('right','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',202/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',203/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',204/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',205/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',206/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',207/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',208/cnt*100)) .. '%' .. ' )'))
    onKey('left','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',209/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',210/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',211/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',212/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',213/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',214/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',215/cnt*100)) .. '%' .. ' )'))
    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',216/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',217/cnt*100)) .. '%' .. ' )'))
    onKey('4','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',218/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',219/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',220/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',221/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',222/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',223/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',224/cnt*100)) .. '%' .. ' )'))
    onKey('3','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',225/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',226/cnt*100)) .. '%' .. ' )'))
    onKey('6','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',227/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',228/cnt*100)) .. '%' .. ' )'))
    onKey('5','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',229/cnt*100)) .. '%' .. ' )'))
    onKey('2','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',230/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',231/cnt*100)) .. '%' .. ' )'))
    onKey('1','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',232/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',233/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',234/cnt*100)) .. '%' .. ' )'))
    onKey('0','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',235/cnt*100)) .. '%' .. ' )'))

    while(platformContext.game.bottomMenu.character.executionTimer~= nil and( 0<#platformContext.game.bottomMenu.character.queue.actions or platformContext.game.bottomMenu.character.onP1 or platformContext.game.bottomMenu.character.onP2 or platformContext.game.bottomMenu.character.onLoop) )do
        start()
    end

    --Must run one more time, to get path coverage in end of execution
    --start()
    lunit.assert_true(platformContext.game.bottomMenu.character.hasWon)
    lunit.assert_true(true)

    onKey('ok','down')
    print('System testing progress ( ' .. (tonumber(string.format('%.1f',236/cnt*100)) .. '%' .. ' )'))


end