require "games.Progg.BottomMenu"
require "games.Progg.BuildArea"
require "games.Progg.Character"
require "games.Progg.Commands"
require "games.Progg.DrawBottomMenu"
require "games.Progg.DrawBuildArea"
require "games.Progg.DrawRightMenu"
require "games.Progg.Map"
require "games.Progg.Position"
require "games.Progg.progg_skin"
require "games.Progg.ProggGame"
require "games.Progg.Queue"
require "games.Progg.RightMenu"
require "games.Progg.Tile"

require "games.GameFactory"

require "menus.ChooseAvatar"
require "menus.CreateProfile"
require "menus.Games"
require "menus.MainMenu"
require "menus.ProfileSelection"
require "menus.skin"

require "platform.PlatformContext"
require "platform.PlatformMenu"

require "toolkit.Controllable"
require "toolkit.Event"
require "toolkit.EventHandler"
require "toolkit.EventListener"
require "toolkit.Game"
require "toolkit.Hook"
require "toolkit.MenuSuperClass"
require "toolkit.Object"

require "main"