require "tests.integration_testing.test_command_and_queue"
-- require "tests.integration_testing.test_command_queue_bottomMenu"
require "tests.integration_testing.inttest_id_1"
--require "tests.integration_testing.inttest_id_2"
require "tests.integration_testing.inttest_id_3"
require "tests.integration_testing.inttest_id_4"
require "tests.integration_testing.inttest_id_5"
--require "tests.integration_testing.inttest_id_6"